import { TopBar } from "@/components/ui/TopBar";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={inter.className + "h-full w-full"}>
        <div className="h-full w-screen overflow-hidden min-h-full box-border relative ">
          <main className="">
            {children}
            <Toaster />
          </main>
          <div className="absolute top-0 w-screen backdrop-blur pt-safe" />
          <header className="absolute right-0 top-0 w-fit mt-safe">
            <TopBar />
          </header>
        </div>
      </body>
    </html>
  );
}
