import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { TopBarRight } from "@/components/ui/TopBarRight";
import { TopBarLeft } from "@/components/ui/TopBarLeft";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={inter.className + "h-full w-full"}>
        <div className="h-full w-screen overflow-hidden min-h-full box-border relative ">
          <main className="">
            {children}
            <Toaster />
          </main>
          <div className="absolute top-0 w-screen backdrop-blur pt-safe" />
          <header className="absolute left-0 top-0 w-fit mt-safe">
            <TopBarLeft />
          </header>
          <header className="absolute right-0 top-0 w-fit mt-safe">
            <TopBarRight />
          </header>
        </div>
      </body>
    </html>
  );
}
